// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLID99SRJycN5fXQDX7cj6PmF3pORjo1w',
    appId: '1:332207072963:web:ab5b1fc1df533e88c92476',
    messagingSenderId: '332207072963',
    projectId: 'asha-62937',
    authDomain: 'asha-62937.firebaseapp.com',
    storageBucket: 'asha-62937.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArmtuBDpkGu1XQG2fhWk4Qz-Nq7pxMsWo',
    appId: '1:332207072963:android:ad025c0dd6df17bfc92476',
    messagingSenderId: '332207072963',
    projectId: 'asha-62937',
    storageBucket: 'asha-62937.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKGPutoP-0G7yQnfORc4nTHbvzfAyVwzQ',
    appId: '1:332207072963:ios:be479b6b071875cfc92476',
    messagingSenderId: '332207072963',
    projectId: 'asha-62937',
    storageBucket: 'asha-62937.appspot.com',
    iosClientId: '332207072963-i9amp3e1fngpvvaiem62v6rn4qk0djlg.apps.googleusercontent.com',
    iosBundleId: 'com.example.ashaProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKGPutoP-0G7yQnfORc4nTHbvzfAyVwzQ',
    appId: '1:332207072963:ios:be479b6b071875cfc92476',
    messagingSenderId: '332207072963',
    projectId: 'asha-62937',
    storageBucket: 'asha-62937.appspot.com',
    iosClientId: '332207072963-i9amp3e1fngpvvaiem62v6rn4qk0djlg.apps.googleusercontent.com',
    iosBundleId: 'com.example.ashaProject',
  );
}
